# Generated by Django 4.0.4 on 2022-04-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('artist_name', models.CharField(max_length=100)),
                ('number_of_songs', models.IntegerField()),
                ('genre', models.TextField(max_length=100)),
                ('release_date', models.CharField(max_length=50)),
            ],
        ),
    ]
