# Generated by Django 4.0.4 on 2022-04-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_album_release_date_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='listeners',
            field=models.ManyToManyField(to='main_app.listener'),
        ),
    ]
