# Generated by Django 4.0.4 on 2022-06-03 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_album_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='release_date',
            new_name='release_year',
        ),
    ]
